import { NewAddress } from '@/lib/definitions';

export const placeholderAddresses: NewAddress[] = [
  {
    lastName: 'Kiss',
    firstName: 'Péter',
    city: 'Budapest',
    address: 'Fő utca 1.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Nagy',
    firstName: 'Anna',
    city: 'Budapest',
    address: 'Piac utca 12.',
    dietaryRestrictions: ['glutén'],
  },
  {
    lastName: 'Tóth',
    firstName: 'László',
    city: 'Budapest',
    address: 'Dózsa György utca 5.',
    dietaryRestrictions: ['laktóz'],
  },
  {
    lastName: 'Szabó',
    firstName: 'Éva',
    city: 'Budapest',
    address: 'Kossuth tér 3.',
    dietaryRestrictions: ['mogyoró'],
  },
  {
    lastName: 'Kovács',
    firstName: 'Gábor',
    city: 'Budapest',
    address: 'Arany János utca 8.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Varga',
    firstName: 'Judit',
    city: 'Budapest',
    address: 'Petőfi Sándor utca 21.',
    dietaryRestrictions: [],
    doesHaveTreats: false,
  },
  {
    lastName: 'Molnár',
    firstName: 'Balázs',
    city: 'Budapest',
    address: 'Rákóczi út 42.',
    dietaryRestrictions: ['dió'],
  },
  {
    lastName: 'Farkas',
    firstName: 'Rita',
    city: 'Budapest',
    address: 'Bajcsy-Zsilinszky út 2.',
    dietaryRestrictions: ['glutén', 'laktóz'],
  },
  {
    lastName: 'Horváth',
    firstName: 'Péter',
    city: 'Budapest',
    address: 'Várkörút 10.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Papp',
    firstName: 'Anita',
    city: 'Budapest',
    address: 'Jókai utca 14.',
    dietaryRestrictions: ['mogyoró', 'dió'],
  },
  {
    lastName: 'Balogh',
    firstName: 'István',
    city: 'Budapest',
    address: 'Fő tér 6.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Kissné Szűcs',
    firstName: 'Marianna',
    city: 'Budapest',
    address: 'Dobó István utca 7.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Bálint',
    firstName: 'Zoltán',
    city: 'Budapest',
    address: 'Kossuth Lajos utca 9.',
    dietaryRestrictions: ['glutén', 'laktóz'],
  },
  {
    lastName: 'Gulyás',
    firstName: 'Petra',
    city: 'Budapest',
    address: 'Ady Endre utca 16.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Németh',
    firstName: 'Roland',
    city: 'Budapest',
    address: 'Bartók Béla utca 11.',
    dietaryRestrictions: ['mogyoró'],
  },
  {
    lastName: 'Simon',
    firstName: 'Andrea',
    city: 'Budapest',
    address: 'Fő utca 4.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Vass',
    firstName: 'Gábor',
    city: 'Budapest',
    address: 'Dózsa György út 30.',
    dietaryRestrictions: [],
    doesHaveTreats: false,
  },
  {
    lastName: 'Török',
    firstName: 'Lilla',
    city: 'Budapest',
    address: 'Csengery utca 18.',
    dietaryRestrictions: ['laktóz', 'tojás'],
  },
  {
    lastName: 'Király',
    firstName: 'Attila',
    city: 'Budapest',
    address: 'Petőfi Sándor sétány 3.',
    dietaryRestrictions: ['dió'],
  },
  {
    lastName: 'Fodor',
    firstName: 'Katalin',
    city: 'Debrecen',
    address: 'Rákóczi út 2.',
    dietaryRestrictions: ['glutén'],
  },
  {
    lastName: 'Oláh',
    firstName: 'Zsuzsa',
    city: 'Debrecen',
    address: 'Tisza út 27.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Rácz',
    firstName: 'András',
    city: 'Debrecen',
    address: 'Kossuth utca 19.',
    dietaryRestrictions: ['glutén', 'mogyoró'],
  },
  {
    lastName: 'Szakács',
    firstName: 'Éva',
    city: 'Debrecen',
    address: 'Petőfi Sándor utca 5.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Majoros',
    firstName: 'Gergely',
    city: 'Debrecen',
    address: 'Hősök tere 1.',
    dietaryRestrictions: [],
    doesHaveTreats: false,
  },
  {
    lastName: 'Pál',
    firstName: 'Beáta',
    city: 'Debrecen',
    address: 'Fő utca 20.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Szécsi',
    firstName: 'Márta',
    city: 'Debrecen',
    address: 'Kossuth Lajos utca 8.',
    dietaryRestrictions: ['laktóz'],
  },
  {
    lastName: 'Vörös',
    firstName: 'Levente',
    city: 'Debrecen',
    address: 'Vár utca 12.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Debreceni',
    firstName: 'Klára',
    city: 'Debrecen',
    address: 'Szent István király út 22.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Barta',
    firstName: 'Norbert',
    city: 'Szeged',
    address: 'Vár utca 6.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Kerekes',
    firstName: 'Julianna',
    city: 'Szeged',
    address: 'Petőfi utca 9.',
    dietaryRestrictions: ['glutén'],
  },
  {
    lastName: 'Máthé',
    firstName: 'Roland',
    city: 'Szeged',
    address: 'Rév utca 3.',
    dietaryRestrictions: ['mogyoró'],
  },
  {
    lastName: 'Lukács',
    firstName: 'Noémi',
    city: 'Szeged',
    address: 'Tagore sétány 1.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Sipos',
    firstName: 'Ferenc',
    city: 'Szeged',
    address: 'Duna korzó 7.',
    dietaryRestrictions: ['dió'],
  },
  {
    lastName: 'Bognár',
    firstName: 'Erika',
    city: 'Szeged',
    address: 'Szabadság út 18.',
    dietaryRestrictions: [],
    doesHaveTreats: false,
  },
  {
    lastName: 'Fülöp',
    firstName: 'Imre',
    city: 'Szeged',
    address: 'Május 1. tér 2.',
    dietaryRestrictions: ['laktóz'],
  },
  {
    lastName: 'Erdei',
    firstName: 'Kata',
    city: 'Szeged',
    address: 'Kossuth tér 10.',
    dietaryRestrictions: ['glutén'],
  },
  {
    lastName: 'Vári',
    firstName: 'Béla',
    city: 'Szeged',
    address: 'Várkerület 4.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Tóthné Molnár',
    firstName: 'Réka',
    city: 'Szeged',
    address: 'Rákóczi út 5.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Benkő',
    firstName: 'Sára',
    city: 'Miskolc',
    address: 'Fő utca 24.',
    dietaryRestrictions: ['dió'],
  },
  {
    lastName: 'Csáki',
    firstName: 'Zsolt',
    city: 'Miskolc',
    address: 'Köztársaság út 3.',
    dietaryRestrictions: ['mogyoró', 'laktóz'],
  },
  {
    lastName: 'Kocsis',
    firstName: 'Melinda',
    city: 'Miskolc',
    address: 'Széchenyi tér 2.',
    dietaryRestrictions: ['mogyoró', 'dió'],
  },
  {
    lastName: 'Kiss',
    firstName: 'Roland',
    city: 'Miskolc',
    address: 'Fő tér 11.',
    dietaryRestrictions: [],
    doesHaveTreats: false,
  },
  {
    lastName: 'Lakatos',
    firstName: 'Orsolya',
    city: 'Miskolc',
    address: 'Fő utca 7.',
    dietaryRestrictions: ['glutén'],
  },
  {
    lastName: 'Szalai',
    firstName: 'Tamás',
    city: 'Miskolc',
    address: 'Kossuth Lajos utca 2.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Gábor',
    firstName: 'Dóra',
    city: 'Miskolc',
    address: 'Rákóczi utca 6.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Halász',
    firstName: 'Zoltán',
    city: 'Miskolc',
    address: 'Fő út 13.',
    dietaryRestrictions: ['tojás'],
  },
  {
    lastName: 'Urbán',
    firstName: 'Nóra',
    city: 'Miskolc',
    address: 'Petőfi utca 9.',
    dietaryRestrictions: ['laktóz'],
  },
  {
    lastName: 'Rózsa',
    firstName: 'Péter',
    city: 'Miskolc',
    address: 'Kossuth utca 14.',
    dietaryRestrictions: ['mogyoró'],
  },
  {
    lastName: 'Kiss',
    firstName: 'Gergely',
    city: 'Miskolc',
    address: 'Fő tér 1.',
    dietaryRestrictions: [],
  },
  {
    lastName: 'Molnár',
    firstName: 'Emese',
    city: 'Miskolc',
    address: 'Béke út 5.',
    dietaryRestrictions: [],
  },
];
